-- Seed script to create fake profiles for testing
-- Run this in Supabase SQL Editor

-- First, let's create some fake user IDs (UUIDs)
-- These will be inserted into the auth.users table first, then into public.users

-- NOTE: You'll need to create auth users first via Supabase Auth or use the approach below
-- For testing, we can directly insert into public.users table if RLS allows

-- Clean up any existing test data (optional - uncomment if needed)
-- DELETE FROM public.users WHERE email LIKE '%@testuser.com';

-- Insert fake female profiles
INSERT INTO public.users (
  id, email, first_name, last_name, gender, dob, height, ethnicity, nationality,
  marital_status, has_children, religious_practice, sect, education, profession,
  bio, photos, hobbies, created_at, updated_at, last_active_at, onboarding_completed
) VALUES
-- Female Profile 1 - Arab, Never Married, Very Practicing
(
  gen_random_uuid(),
  'fatima.test1@testuser.com',
  'Fatima',
  'Al-Hassan',
  'female',
  '1995-03-15',
  '165 cm',
  'Arab',
  'Saudi Arabia',
  'Never Married',
  false,
  'very_practicing',
  'Sunni',
  'Bachelor''s Degree',
  'Software Engineer',
  'Assalamu alaikum! Looking for someone who shares my values and faith. I love reading, hiking, and spending time with family.',
  ARRAY['https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400'],
  ARRAY['Reading', 'Hiking', 'Cooking'],
  NOW(),
  NOW(),
  NOW(),
  true
),
-- Female Profile 2 - South Asian, Divorced, Practicing
(
  gen_random_uuid(),
  'aisha.test2@testuser.com',
  'Aisha',
  'Khan',
  'female',
  '1990-07-22',
  '160 cm',
  'South Asian',
  'Pakistan',
  'Divorced',
  true,
  'practicing',
  'Sunni',
  'Master''s Degree',
  'Doctor',
  'Alhamdulillah for everything. Single mom looking for a kind and understanding partner.',
  ARRAY['https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400'],
  ARRAY['Medicine', 'Travel', 'Photography'],
  NOW(),
  NOW(),
  NOW(),
  true
),
-- Female Profile 3 - African, Never Married, Moderately Practicing
(
  gen_random_uuid(),
  'khadija.test3@testuser.com',
  'Khadija',
  'Ibrahim',
  'female',
  '1998-11-08',
  '170 cm',
  'African',
  'Nigeria',
  'Never Married',
  false,
  'moderately_practicing',
  'Sunni',
  'Bachelor''s Degree',
  'Marketing Manager',
  'Creative soul with a love for art and culture. Looking for my best friend and partner in life.',
  ARRAY['https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400'],
  ARRAY['Art', 'Music', 'Fashion'],
  NOW(),
  NOW(),
  NOW(),
  true
),
-- Female Profile 4 - Mixed, Widowed, Very Practicing
(
  gen_random_uuid(),
  'maryam.test4@testuser.com',
  'Maryam',
  'Abdullah',
  'female',
  '1988-05-30',
  '158 cm',
  'Mixed',
  'United Kingdom',
  'Widowed',
  true,
  'very_practicing',
  'Sunni',
  'PhD',
  'University Professor',
  'Seeking a compassionate soul for this journey of life. Faith, family, and knowledge are my priorities.',
  ARRAY['https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400'],
  ARRAY['Teaching', 'Writing', 'Gardening'],
  NOW(),
  NOW(),
  NOW(),
  true
),
-- Female Profile 5 - European, Never Married, Not Practicing
(
  gen_random_uuid(),
  'sarah.test5@testuser.com',
  'Sarah',
  'Ahmed',
  'female',
  '1996-09-12',
  '175 cm',
  'European',
  'Germany',
  'Never Married',
  false,
  'not_practicing',
  'Sunni',
  'Bachelor''s Degree',
  'Graphic Designer',
  'Cultural Muslim, open-minded and adventurous. Love traveling and trying new cuisines!',
  ARRAY['https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400'],
  ARRAY['Design', 'Travel', 'Food'],
  NOW(),
  NOW(),
  NOW(),
  true
),
-- Female Profile 6 - North African, Never Married, Practicing
(
  gen_random_uuid(),
  'layla.test6@testuser.com',
  'Layla',
  'Benali',
  'female',
  '1993-02-28',
  '162 cm',
  'North African',
  'Morocco',
  'Never Married',
  false,
  'practicing',
  'Sunni',
  'Master''s Degree',
  'Architect',
  'Passionate about design and creating beautiful spaces. Looking for someone who appreciates both deen and dunya.',
  ARRAY['https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400'],
  ARRAY['Architecture', 'Interior Design', 'Calligraphy'],
  NOW(),
  NOW(),
  NOW(),
  true
),
-- Female Profile 7 - East Asian, Annulled, Moderately Practicing
(
  gen_random_uuid(),
  'amina.test7@testuser.com',
  'Amina',
  'Wong',
  'female',
  '1991-12-05',
  '155 cm',
  'East Asian',
  'Malaysia',
  'Annulled',
  false,
  'moderately_practicing',
  'Sunni',
  'Bachelor''s Degree',
  'Business Analyst',
  'Starting fresh and optimistic about the future. Love good conversations and cozy coffee shops.',
  ARRAY['https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400'],
  ARRAY['Business', 'Coffee', 'Reading'],
  NOW(),
  NOW(),
  NOW(),
  true
),
-- Female Profile 8 - Arab, Never Married, Practicing (Younger)
(
  gen_random_uuid(),
  'noor.test8@testuser.com',
  'Noor',
  'Khalil',
  'female',
  '2000-06-18',
  '168 cm',
  'Arab',
  'Jordan',
  'Never Married',
  false,
  'practicing',
  'Sunni',
  'Bachelor''s Degree',
  'Content Creator',
  'Young, ambitious, and seeking someone equally driven. Love creating content and inspiring others.',
  ARRAY['https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400'],
  ARRAY['Social Media', 'Fitness', 'Fashion'],
  NOW(),
  NOW(),
  NOW(),
  true
);

-- Insert fake male profiles
INSERT INTO public.users (
  id, email, first_name, last_name, gender, dob, height, ethnicity, nationality,
  marital_status, has_children, religious_practice, sect, education, profession,
  bio, photos, hobbies, created_at, updated_at, last_active_at, onboarding_completed
) VALUES
-- Male Profile 1 - Arab, Never Married, Very Practicing
(
  gen_random_uuid(),
  'omar.test1@testuser.com',
  'Omar',
  'Al-Farsi',
  'male',
  '1992-04-20',
  '180 cm',
  'Arab',
  'UAE',
  'Never Married',
  false,
  'very_practicing',
  'Sunni',
  'Master''s Degree',
  'Civil Engineer',
  'Seeking a righteous partner to build a family based on Islamic values. I pray 5 times daily and fast regularly.',
  ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400'],
  ARRAY['Engineering', 'Sports', 'Reading Quran'],
  NOW(),
  NOW(),
  NOW(),
  true
),
-- Male Profile 2 - South Asian, Divorced, Practicing
(
  gen_random_uuid(),
  'ahmed.test2@testuser.com',
  'Ahmed',
  'Rahman',
  'male',
  '1988-08-15',
  '175 cm',
  'South Asian',
  'Bangladesh',
  'Divorced',
  true,
  'practicing',
  'Sunni',
  'PhD',
  'Research Scientist',
  'Father of one, looking for someone understanding and kind. I believe in second chances and the mercy of Allah.',
  ARRAY['https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400'],
  ARRAY['Science', 'Parenting', 'Nature'],
  NOW(),
  NOW(),
  NOW(),
  true
),
-- Male Profile 3 - African, Never Married, Moderately Practicing
(
  gen_random_uuid(),
  'ibrahim.test3@testuser.com',
  'Ibrahim',
  'Okonkwo',
  'male',
  '1995-01-25',
  '185 cm',
  'African',
  'Kenya',
  'Never Married',
  false,
  'moderately_practicing',
  'Sunni',
  'Bachelor''s Degree',
  'Financial Analyst',
  'Ambitious professional with a balanced approach to life and deen. Looking for my partner in faith and life.',
  ARRAY['https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400'],
  ARRAY['Finance', 'Football', 'Volunteering'],
  NOW(),
  NOW(),
  NOW(),
  true
),
-- Male Profile 4 - Mixed, Widowed, Very Practicing
(
  gen_random_uuid(),
  'yusuf.test4@testuser.com',
  'Yusuf',
  'Martinez',
  'male',
  '1985-10-03',
  '178 cm',
  'Mixed',
  'Spain',
  'Widowed',
  true,
  'very_practicing',
  'Sunni',
  'Master''s Degree',
  'School Principal',
  'Revert Muslim, strong in faith. Looking for a pious partner who can be a mother figure to my children.',
  ARRAY['https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400'],
  ARRAY['Education', 'Islamic Studies', 'Community Work'],
  NOW(),
  NOW(),
  NOW(),
  true
),
-- Male Profile 5 - European, Never Married, Not Practicing
(
  gen_random_uuid(),
  'ali.test5@testuser.com',
  'Ali',
  'Mueller',
  'male',
  '1997-07-08',
  '182 cm',
  'European',
  'Austria',
  'Never Married',
  false,
  'not_practicing',
  'Sunni',
  'Bachelor''s Degree',
  'Software Developer',
  'Tech enthusiast, cultural Muslim. Looking for someone open-minded who enjoys the good things in life.',
  ARRAY['https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400'],
  ARRAY['Coding', 'Gaming', 'Traveling'],
  NOW(),
  NOW(),
  NOW(),
  true
),
-- Male Profile 6 - North African, Never Married, Practicing
(
  gen_random_uuid(),
  'karim.test6@testuser.com',
  'Karim',
  'Bouazizi',
  'male',
  '1994-03-12',
  '177 cm',
  'North African',
  'Tunisia',
  'Never Married',
  false,
  'practicing',
  'Sunni',
  'Master''s Degree',
  'Pharmacist',
  'Healthcare professional with strong family values. Looking for a partner to share life''s journey with.',
  ARRAY['https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400'],
  ARRAY['Healthcare', 'Football', 'Cooking'],
  NOW(),
  NOW(),
  NOW(),
  true
),
-- Male Profile 7 - Central Asian, Annulled, Moderately Practicing
(
  gen_random_uuid(),
  'timur.test7@testuser.com',
  'Timur',
  'Karimov',
  'male',
  '1990-09-28',
  '183 cm',
  'Central Asian',
  'Uzbekistan',
  'Annulled',
  false,
  'moderately_practicing',
  'Sunni',
  'Bachelor''s Degree',
  'Restaurant Owner',
  'Entrepreneur with a passion for halal food and culture. Looking for a supportive partner.',
  ARRAY['https://images.unsplash.com/photo-1534030347209-467a5b0ad3e6?w=400'],
  ARRAY['Business', 'Cooking', 'Hospitality'],
  NOW(),
  NOW(),
  NOW(),
  true
),
-- Male Profile 8 - Arab, Never Married, Practicing (Younger)
(
  gen_random_uuid(),
  'hassan.test8@testuser.com',
  'Hassan',
  'El-Masri',
  'male',
  '1999-11-15',
  '176 cm',
  'Arab',
  'Egypt',
  'Never Married',
  false,
  'practicing',
  'Sunni',
  'Bachelor''s Degree',
  'Medical Student',
  'Future doctor with big dreams. Looking for someone patient and supportive as I complete my studies.',
  ARRAY['https://images.unsplash.com/photo-1544723795-3fb6469f5b39?w=400'],
  ARRAY['Medicine', 'Basketball', 'Video Games'],
  NOW(),
  NOW(),
  NOW(),
  true
);

-- Verify the inserted profiles
SELECT 
  first_name, 
  last_name, 
  gender, 
  ethnicity, 
  marital_status, 
  has_children, 
  religious_practice,
  EXTRACT(YEAR FROM AGE(dob::date)) as age
FROM public.users 
WHERE email LIKE '%@testuser.com'
ORDER BY gender, first_name;

